###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "mgmg",
    "password": "testtest123"
}
###
GET http://localhost:3000/sets
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjBjMTI1Yjk2MDNhNDUwMDUzYWQyYyIsImlhdCI6MTYzOTA1OTUxMiwiZXhwIjoxNjM5MDYxMzEyfQ.rk74QOE6BkEW7ovOPz-q4fjaiFxx4-N27pvlV2T2aFA
###
POST http://localhost:3000/resetPassword
Content-Type: application/json

{
    "username": "daddsas"
}
###
POST http://localhost:3000/refresh
