###
GET http://localhost:3000/signup
Content-Type: application/json

{
    "email": "tedascik@koxuwa.com",
    "username": "daddsas",
    "password": "siema1234"
}
###
GET http://localhost:3000/refresh
###
POST http://localhost:3000/resetPassword
Content-Type: application/json

{
    "username": "daddsas"
}