###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "test@test.pl",
    "username": "test",
    "password": "testtest123"
}
###
GET http://localhost:3000/sets
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODQzYjM1MWI4ZDNjNDFkOGVlZWYwZSIsImlhdCI6MTYzODU1MTM2OCwiZXhwIjoxNjM4NTUzMTY4fQ.wwE2Qto2dqIgKdk5URTBiviRwL4K2WCDtQoTMBqAW0o
###
POST http://localhost:3000/resetPassword
Content-Type: application/json

{
    "username": "daddsas"
}
###
POST http://localhost:3000/refresh
