const config = {
    ACCESS_TOKEN: '',
    ACCESS_TOKEN_EXPIRES_IN_SECONDS: 1800,
    REFRESH_TOKEN: '',
    REFRESH_TOKEN_EXPIRES: "7 days",
    REFRESH_TOKEN_EXPIRES_IN_MILISECONDS: 604800000,
    DB_PASSWORD: '',
    DB_USERNAME: '',
    DB_HOST : '',
    DB_NAME: '',
    HASHED_PASSWORD_LENGTH: 0,
    SENDGRID_API_KEY: ''
}

module.exports = config;